[package]
name = "portman"
version = "0.1.0"
description = "A local server manager"
authors = ["PortMan"]
edition = "2021"

[lib]
name = "portman_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
maxminddb = "0.27"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
sha2 = "0.10"
sysinfo = "0.39.6"
tauri = { version = "2", features = [] }
tauri-plugin-global-shortcut = "2"
thiserror = "2"
